name: Master
on:
  schedule:
    - cron: '10 0/1 * * *'

  workflow_dispatch:

jobs:
  check_latest_commit:

    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: print latest_commit
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: true
        name: check whether latest commit is within two hours.
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list --after="1 hour" ${{ github.sha }}) && echo "::set-output name=should_run::false"

  build:

    needs: check_latest_commit
    if: ${{ needs.check_latest_commit.outputs.should_run != 'false' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Running
      run: |
        echo "Running! & Testing2"
