name: test

on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check
        run: |
          echo "testing"
